apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zammad.fullname" . }}-websocket
  labels:
    {{- include "zammad.labels" . | nindent 4 }}
    app.kubernetes.io/component: zammad-websocket
  annotations:
    {{- include "zammad.annotations" . | nindent 4 }}
spec:
  replicas: 1 # Not scalable, may only run once per cluster.
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "zammad.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "zammad.podAnnotations" . | nindent 8 }}
        {{- with .Values.zammadConfig.websocket.podAnnotations }}
        {{- toYaml . | nindent 8}}
        {{- end }}
      labels:
        {{- include "zammad.podLabels" . | nindent 8 }}
        app.kubernetes.io/component: zammad-websocket
        {{- with .Values.zammadConfig.websocket.podLabels }}
        {{- toYaml . | nindent 8}}
        {{- end }}
    spec:
      {{- include "zammad.podSpec.deployment" . | nindent 6 }}
      {{- with .Values.zammadConfig.websocket.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        {{- with .Values.zammadConfig.websocket.sidecars }}
        {{- toYaml . | nindent 8}}
        {{- end }}
        - name: zammad-websocket
          {{- include "zammad.containerSpec" (merge (dict "containerConfig" .Values.zammadConfig.websocket) .) | nindent 10 }}
          command:
            - "bundle"
            - "exec"
            - "script/websocket-server.rb"
            - "-b"
            - "0.0.0.0"
            - "-p"
            - "6042"
            - "start"
          env:
            {{- include "zammad.env" . | nindent 12 }}
            {{- include "zammad.env.failOnPendingMigrations" . | nindent 12 }}
          ports:
            - name: websocket
              containerPort: 6042
          volumeMounts:
            {{- include "zammad.volumeMounts" . | nindent 12 }}
      volumes:
        {{- include "zammad.volumes" . | nindent 8 }}
